# Site settings
title: Trillium Center for Yoga and Health, LLC
email: admin@trilliumyogacenter.com
description: >
  The home of Trillium Center for Yoga and Health, LLC
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.trilliumyogacenter.com" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username:
github_username:  trilliumyogacenter

# Build settings
markdown: kramdown

timezone: America/New_York

datenumbers:
  - day: monday
    value: 0
  - day: tuesday
    value: 1
  - day: wednesday
    value: 2
  - day: thursday
    value: 3
  - day: friday
    value: 4
  - day: saturday
    value: 5
  - day: sunday
    value: 6
