# Site settings
title: Trillium Center for Yoga and Health, LLC
email: admin@trilliumyogacenter.com
description: > 
  The home of Trillium Center for Yoga and Health, LLC
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://trilliumyogacenter.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  trilliumyogacenter

# Build settings
markdown: kramdown
